### ISSUE TITLE
No wifi in A500H + some more problems.

### ISSUE THREAD

**Issue by kazekagesama** [DeadSquirrel01/lineage-15_a5_releases#1]
There is no wifi on A500H ..
There is no mtp support in new twrp 
also updater script has some problems...so i had to remake it to install the rom.
More issues will be report
is there anyway i can fix it?
  
BROWSER DOESNT WORK.PLAY STORE TOO :(

**Comment by DeadSquirrel01** [comment]
The README says "LineageOS 15 releases for galaxy a5 SM-A500FU." If you install on other variants you'll get some problems like RIL, because ril libs are device-specific. You need to replace libsec-ril plus qcom framework libs from stock lp rom of your variant. Anyway wifi isn't device-specific and it should work, but I don't know anything since you didn't provide a logcat. And playstore problem surely isn't a problem of the rom but rather a problem of gapps or something else

**Comment by kazekagesama** [comment]
well..yes..i tried your Lineage 14.1 on A500H .Wifi was working there...but it maybe due to your updater script idk yet..it was just not turning on..I will provide logcats in a while here...also i will redownload gapps and check...and about RIL data packet was sent but was not being recieved.. I will try those libs like i used in 14.1 and inform :)

**Comment by eaangrino** [comment]
The Sim Card does not work.
SM-A500M.
I used the fix to repair the sim card signal for lineage 14.1, but I only fix the filter on the screen and did not solve the sim card signal.

**Comment by DeadSquirrel01** [comment]
Releases are only for a500fu. You can port on other variants, but they aren't supported by me, since as i said, releases are only for FU (you can see it in releases name), and I support only the stuff I publish for the devices I publish. Some device-specific stuff won't work on other variants unless you use you device's libs. So, i can close this now

**Comment by eaangrino** [comment]
Ok man, I was reading and I saw other things to try, I'm going to download 15.1 to test it and see what I can do :).
Could you recommend me some tools that I could use, please, I want to try to make the rom work in my SM-A500M :)
